#!/bin/bash

## This file will activate the virtual environment using venv
## NOTE: you must be in same dir as the ve

## To start the venv, type 
# $ source argVE_start

## To leave the venv, run 
# $ deactivate

## To run flask, type 
# $ flask run


APP="discusso.py"
VE="discussoVE"

## activate the venv
source ./$VE/bin/activate

## set FlASK_APP to name of app
export FLASK_APP=$APP

