"""empty message

Revision ID: 5c7b3795f56d
Revises: 38d21728421d
Create Date: 2019-05-17 14:45:16.480479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7b3795f56d'
down_revision = '38d21728421d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reply', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reply', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reply', type_='foreignkey')
    op.drop_column('reply', 'user_id')
    # ### end Alembic commands ###
