"""add reply, user and post tables

Revision ID: 60d49e1a3b24
Revises: 19d73f2166c8
Create Date: 2019-04-25 13:55:02.377849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d49e1a3b24'
down_revision = '19d73f2166c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=248), nullable=True),
    sa.Column('blesses', sa.Integer(), nullable=True),
    sa.Column('curses', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('stance', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reply_timestamp'), 'reply', ['timestamp'], unique=False)
    op.add_column('post', sa.Column('blesses', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('curses', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('desc', sa.String(length=248), nullable=True))
    op.add_column('post', sa.Column('title', sa.String(length=64), nullable=True))
    op.drop_column('post', 'body')
    op.add_column('user', sa.Column('bio', sa.String(length=248), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('passwd_hash', sa.String(length=128), nullable=True))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('user', 'passwd_hash')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'bio')
    op.add_column('post', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('post', 'title')
    op.drop_column('post', 'desc')
    op.drop_column('post', 'curses')
    op.drop_column('post', 'blesses')
    op.drop_index(op.f('ix_reply_timestamp'), table_name='reply')
    op.drop_table('reply')
    # ### end Alembic commands ###
